# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alert_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alert_data.proto',
  package='hiota',
  syntax='proto3',
  serialized_options=_b('\n\037com.hitachivantara.hiota.modelsB\016HiotaAlertDataP\001ZBgitlab-edge.eng.hitachivantara.com/pandora/shared/proto/pkg/models\370\001\001\242\002\013HiotaModels\252\002\033HitachiVantara.Hiota.Models'),
  serialized_pb=_b('\n\x10\x61lert_data.proto\x12\x05hiota\"\xb9\x03\n\tAlertData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x30\n\x08severity\x18\x03 \x01(\x0e\x32\x1e.hiota.AlertData.AlertSeverity\x12(\n\x04type\x18\x04 \x01(\x0e\x32\x1a.hiota.AlertData.AlertType\"\x7f\n\rAlertSeverity\x12\x1a\n\x16\x41LERT_SEVERITY_UNKNOWN\x10\x00\x12\x19\n\x15\x41LERT_SEVERITY_NORMAL\x10\x01\x12\x1a\n\x16\x41LERT_SEVERITY_WARNING\x10\x02\x12\x1b\n\x17\x41LERT_SEVERITY_CRITICAL\x10\x03\"\xab\x01\n\tAlertType\x12\x16\n\x12\x41LERT_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11\x41LERT_TYPE_CUSTOM\x10\x01\x12\x17\n\x13\x41LERT_TYPE_HIGH_CPU\x10\x02\x12\x1a\n\x16\x41LERT_TYPE_HIGH_MEMORY\x10\x03\x12\x1d\n\x19\x41LERT_TYPE_LOW_DISK_SPACE\x10\x04\x12\x1b\n\x17\x41LERT_TYPE_SERVICE_DOWN\x10\x05\x42\xa6\x01\n\x1f\x63om.hitachivantara.hiota.modelsB\x0eHiotaAlertDataP\x01ZBgitlab-edge.eng.hitachivantara.com/pandora/shared/proto/pkg/models\xf8\x01\x01\xa2\x02\x0bHiotaModels\xaa\x02\x1bHitachiVantara.Hiota.Modelsb\x06proto3')
)



_ALERTDATA_ALERTSEVERITY = _descriptor.EnumDescriptor(
  name='AlertSeverity',
  full_name='hiota.AlertData.AlertSeverity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALERT_SEVERITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_SEVERITY_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_SEVERITY_WARNING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_SEVERITY_CRITICAL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=168,
  serialized_end=295,
)
_sym_db.RegisterEnumDescriptor(_ALERTDATA_ALERTSEVERITY)

_ALERTDATA_ALERTTYPE = _descriptor.EnumDescriptor(
  name='AlertType',
  full_name='hiota.AlertData.AlertType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_CUSTOM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_HIGH_CPU', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_HIGH_MEMORY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_LOW_DISK_SPACE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_TYPE_SERVICE_DOWN', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=298,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_ALERTDATA_ALERTTYPE)


_ALERTDATA = _descriptor.Descriptor(
  name='AlertData',
  full_name='hiota.AlertData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hiota.AlertData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hiota.AlertData.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='severity', full_name='hiota.AlertData.severity', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='hiota.AlertData.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ALERTDATA_ALERTSEVERITY,
    _ALERTDATA_ALERTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=469,
)

_ALERTDATA.fields_by_name['severity'].enum_type = _ALERTDATA_ALERTSEVERITY
_ALERTDATA.fields_by_name['type'].enum_type = _ALERTDATA_ALERTTYPE
_ALERTDATA_ALERTSEVERITY.containing_type = _ALERTDATA
_ALERTDATA_ALERTTYPE.containing_type = _ALERTDATA
DESCRIPTOR.message_types_by_name['AlertData'] = _ALERTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlertData = _reflection.GeneratedProtocolMessageType('AlertData', (_message.Message,), dict(
  DESCRIPTOR = _ALERTDATA,
  __module__ = 'alert_data_pb2'
  # @@protoc_insertion_point(class_scope:hiota.AlertData)
  ))
_sym_db.RegisterMessage(AlertData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
